"use strict";

(function () {
  //store dummy restaurant list globally to demo site. This data will come from backend mongodb
  let restaurants = [
    {
      id: "rest1",
      name: "Chinese Dragon",
      cuisine: "chinese",
      info: "Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa.",
      image: "img/chinese.jpg",
      schedule: [
        {
          day: 0,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 1,
          times: [
            { time: "11:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "12:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 2,
          times: [
            { time: "11:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 3,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: ["user1234"] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 4,
          times: [
            { time: "11:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: [] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: [] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "20:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 5,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:30", tables: [] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: [] },
            { time: "21:30", tables: [] },
          ],
          max: 3,
        },
        {
          day: 6,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "13:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "14:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 7,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
      ],
    },
    {
      id: "rest2",
      name: "Spice Is Right",
      cuisine: "Indian",
      info: "Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa.",
      image: "img/indian.jpg",
      schedule: [
        {
          day: 0,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: [] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "20:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: [] },
          ],
          max: 3,
        },
        {
          day: 1,
          times: [
            { time: "11:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "11:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "12:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "12:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "13:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "13:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "20:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 2,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "12:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "13:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "13:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "14:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "20:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 3,
          times: [
            { time: "11:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "11:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: [] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "16:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "16:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 4,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 5,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 6,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 7,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
      ],
    },
    {
      id: "rest3",
      name: "Bella Bella",
      cuisine: "italian",
      info: "Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa.",
      image: "img/italian.jpg",
      schedule: [
        {
          day: 0,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 1,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "14:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 2,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 3,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 4,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 5,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 6,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "12:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "12:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "13:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "13:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "14:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 7,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
      ],
    },
    {
      id: "rest4",
      name: "Next Wave",
      cuisine: "fusion",
      info: "Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa.",
      image: "img/fusion.jpg",
      schedule: [
        {
          day: 0,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "13:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 1,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "16:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 2,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 3,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 4,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 5,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 6,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 7,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
      ],
    },
    {
      id: "rest5",
      name: "Marcell's",
      cuisine: "french",
      info: "Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa.",
      image: "img/french.jpg",
      schedule: [
        {
          day: 0,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 1,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 2,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 3,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 4,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 5,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 6,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: [] },
            { time: "18:00", tables: [] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: ["user1234"] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
        {
          day: 7,
          times: [
            { time: "11:00", tables: [] },
            { time: "11:30", tables: [] },
            { time: "12:00", tables: [] },
            { time: "12:30", tables: [] },
            { time: "13:00", tables: [] },
            { time: "13:30", tables: [] },
            { time: "14:00", tables: [] },
            { time: "14:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "15:00", tables: [] },
            { time: "15:30", tables: [] },
            { time: "16:00", tables: [] },
            { time: "16:30", tables: [] },
            { time: "17:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "17:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "18:30", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "19:30", tables: ["tempId"] },
            { time: "20:00", tables: [] },
            { time: "20:30", tables: [] },
            { time: "21:00", tables: ["tempId", "tempId", "tempId"] },
            { time: "21:30", tables: ["tempId", "tempId", "tempId"] },
          ],
          max: 3,
        },
      ],
    },
  ];

  let users = [
    {
      userId: "user1234",
      email: "user@email.com",
      password: "password",
      reservations: [
        {
          id: 1,
          restaurant: "Chinese Dragon",
          date: "2021-07-16",
          time: "18:00",
          guests: 5,
          mobile: "0408378465",
          requests: "vegan and egg allergy",
          status: "Confirmed",
        },
        {
          id: 2,
          restaurant: "Marcell's",
          date: "2021-07-19",
          time: "20:00",
          guests: 2,
          mobile: "0408378465",
          requests: "window seat",
          status: "Confirmed",
        },
      ],
    },
  ];

  //store dummy user globally to demo site. This data will come from backend mongodb. For html demo its in sessionStorage so can be updated between html reloads
  let demoSessionStarted = sessionStorage.getItem("demoStart");
  if (demoSessionStarted === null) {
    sessionStorage.setItem("userDetails", JSON.stringify(users));
    sessionStorage.setItem("restaurants", JSON.stringify(restaurants));
    sessionStorage.setItem("demoStart", true);
  }
})();
